config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :budgets do
    get "delete"
  end
  
  resources :wallets, :only => [:new, :create, :edit, :update, :destroy]

  root to: 'wallets#new'

  get "*any", via: :all, to: "errors#not_found"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    can :create, Wallet
    can [:update, :destroy], Wallet do |wallet|
      wallet.try(:email) == user.email
    end
  end
end

app/models/budget.rb
class Budget < ActiveRecord::Base
  belongs_to :wallet

  validates :description, presence: true
  validates :amount, presence: true,
            numericality: true,
            format: { :with => /\A\d{1,6}(\.\d{0,2})?\z/ }
  validates :money_kind, presence: true,
            format: { :with => /\A(income|expense)\z/}
  validates_presence_of :wallet_id


  scope :description, -> (description) { where("description like ?", "%#{description}%")}
  scope :money_kind, -> (money_kind) { where money_kind: money_kind }
  scope :start_date, -> (start_date) { where("date >= ?", "#{start_date}")}
  scope :end_date, -> (end_date) { where("date <= ?", "#{end_date}")}
  
  


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :wallet
  #has_many :budgets, :through => :wallet
end

app/models/wallet.rb
class Wallet < ActiveRecord::Base
  belongs_to :user
  has_many :budgets
  
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    flash[:error] = "Access denied"
    redirect_to root_url
  end

  rescue_from ActionView::MissingTemplate do |exception|
     raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  respond_to :html, :js

   before_filter :authenticate_user!
   before_action :get_wallets, only: [:index, :update, :create, :destroy]

  def index
    filtering_params(params).each do |key, value|
      @budgets = @budgets.public_send(key, value) if value.present?
    end
    @wallet_id = Wallet.find_by_email(current_user.email).id
  end

  def new
    @budget = Budget.new
    @type = budget_type
  end

  def create
    @budget = Budget.create(budget_params)

  end

  def edit
    @type = budget_type
    @budget = Budget.find(params[:id])
  end

  def update
    @budget = Budget.find(params[:id])
    
    @budget.update_attributes(budget_params)
  end

  def delete
    @budget = Budget.find(params[:budget_id])
  end

  def destroy
    @budget = Budget.find(params[:id])
    @budget.destroy
  end


private

  def budget_params
    wallet_id = Wallet.find_by_email(current_user.email).id
    params.require(:budget).permit(:description, :amount, :date, :money_kind).merge(wallet_id: wallet_id)
  end

  def get_wallets
    wallet_id = Wallet.find_by_email(current_user.email).id
    @budgets = Budget.where(wallet_id: wallet_id).paginate(:page => params[:page], :per_page => 8).order('date DESC')
  end

  def filtering_params(params)
    params.slice(:description, :money_kind, :start_date, :end_date)
  end


  def budget_type
    wallet = Wallet.find_by_email(current_user.email)
    array ||= []
    array << ['income', 'income'] if (wallet.income == true)
    array << ['expense', 'expense'] if (wallet.expense == true)
    return array
  end

end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  rescue ActionController::UnknownFormat
    render status: 404, text: "nope"
  end
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController

  load_and_authorize_resource except: [:create]
  before_filter :authenticate_user!
  
  before_action :find, only: [:new, :update, :edit, :destroy]


  def show
    @wallet = Wallet.find(params[:user_id])
  end

  def new
    unless @wallet 
      @wallet = Wallet.new
    else
     redirect_to budgets_url
    end
  end

  def create
    @wallet = Wallet.create(wallet_params)
    redirect_to budgets_url
  end

  def edit
    authorize! :edit, @wallet
  end

  def update
    @wallet.update_attributes(wallet_params)
    redirect_to budgets_url
  end

  def destroy
    authorize! :destroy, @wallet
    @wallet.budgets.destroy_all
    @wallet.destroy
    redirect_to root_path
  end

private

  def wallet_params
    params.require(:wallet).permit(:email, :income, :expense).merge(email: current_user.email)
  end

  def find
    @wallet = Wallet.find_by_email(current_user.email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class= "text-danger" id="error_explanation">
      <strong>#{sentence}</strong>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/budgets/_delete.html.erb
<div class="modal-header">
  <h3>Delete item</h3>
</div>
<div class="modal-body">
<ul class="errors"></ul>
Are you sure you wish to delete <b>"<%= @budget.description %>"</b> item?
</div>
<div class="modal-footer">
  <%= link_to "Yes, Delete This item", budget_path(@budget), method: :delete, remote: true, class: "btn btn-danger" %>
  <%= link_to "No, Please Don't", "#", class: "btn", data: { dismiss: "modal" } %>
</div>

app/views/budgets/_edit.html.erb
<div class="modal-header">
  <h3> Edit item</h3>
</div>
<%= render "form" %>

app/views/budgets/_form.html.erb
<%= form_for @budget, remote: true, html: { class: "form-horizontal", style: "display:inline;" } do |f| %>
  <div class="modal-body">
    <ul class="errors"></ul>

    <div class="control-group">
      <%= f.label :description, class:"control-label" %>
      <div class="controls">
        <%= f.text_field :description %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :money_kind, class: "control-label" %>
      <div class="controls">
        <%= f.select(:money_kind, options_for_select(@type)) %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :amount, class: "control-label" %>
      <div class="controls">
        <%= f.text_field :amount %>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :date, class: "control-label" %>
      <div class="controls">
        <%= f.date_select :date %>
      </div>
    </div>
  </div>

  <div class="modal-footer">
    <%= f.submit 'Save Item', class: "btn btn-primary" %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger", "data-dismiss" => "modal" %>
  </div>

<% end %>

app/views/budgets/_index.html.erb
<% @budgets.each do |budget| %>
  <tr>
    <td><%= budget.description %></td>
    <td><%= budget.money_kind %></td>
    <% if budget.money_kind == "income"  %>
      <td class="text-success"><%= number_to_currency budget.amount %></td>
    <% elsif budget.money_kind == "expense"%>
      <td class="text-danger"><%= number_to_currency budget.amount %></td>
    <% end %>
    <td><%= budget.date.strftime("%Y-%m-%d") %></td>
    <td><%= link_to "Edit", edit_budget_path(budget), remote: true, class: "btn btn-primary" %></td>
    <td><%= link_to "Delete", budget_delete_path(budget), remote: true, class: "btn btn-danger" %></td>
  </tr>
<% end %>

app/views/budgets/_new.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
<h3>New item</h3>
</div>

<%= render "form" %>

app/views/budgets/_save.js.erb
$("ul.errors").html("").addClass("text-danger")
<% if @budget.errors.any? %>
  <% @budget.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".budget-index").html("<%= escape_javascript(render 'index') %>")
  $("#budget-modal").modal("hide")
<% end %>

app/views/budgets/create.js.erb
<%= render "save" %>

app/views/budgets/delete.js.erb
$("#inner-budget-modal").html("<%= escape_javascript(render 'delete') %>")
$("#budget-modal").modal("show")

app/views/budgets/destroy.js.erb
<%= render "save" %>

app/views/budgets/edit.js.erb
$("#inner-budget-modal").html("<%= escape_javascript(render 'edit') %>")
$("#budget-modal").modal("show")

app/views/budgets/index.html.erb
<div class="container">
  <div class="well">
    <div class="row">
      <div class="col-xs-4">
        <%= link_to "New budget item", new_budget_path, remote: true, class: "navbar-btn btn btn-primary" %>
      </div>
      <div class="pull-right">
        <%= link_to "Edit wallet", edit_wallet_path(@wallet_id), class: "navbar-btn btn btn-primary" %>
        <%= link_to "Delete wallet", wallet_path(@wallet_id), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: "navbar-btn btn btn-danger" %>
      </div>
    </div>
    </hr>
    <div class="row col-xs-12">
      <p class="text-left"><h3>Filtering of items</h3></p>
    </div>
    <div class="row" id="filter-panel">
      <%= form_tag budgets_path, :method => 'get' do %>
        <div class="col-xs-2">
          <%= text_field_tag :description, params[:description], class: "form-control", placeholder: "Description" %>
        </div>
        <div class="col-xs-2">
          <%= select_tag :money_kind, options_for_select([[ "income", "income" ],["expense", "expense"]]), class: "form-control" %>
        </div>
  
        <div class='col-xs-2'>
           <%= text_field_tag :start_date, params[:start_date], class: "form-control", id: "datepicker", placeholder: "Start date" %>
        </div>

        <div class='col-xs-2'>
           <%= text_field_tag :end_date, params[:end_date], class: "form-control", id: "datepicker2", placeholder: "End date" %>
        </div>

        <script type="text/javascript">
            $(function () {
                $('#datepicker').datepicker({
                  format: 'yyyy-mm-dd'
                });
                $('#datepicker2').datepicker({
                  format: 'yyyy-mm-dd'
                });
            });
        </script>

        <div class="col-xs-2">
          <%= submit_tag "Search", :name => nil, class: "navbar-btn btn btn-primary" %>
          <%= link_to "Reset", budgets_path, class: "navbar-btn btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
  <div class="new-budget"></div>
  
  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th>Description</th>
        <th>Type</th>
        <th>Amount of money</th>
        <th>Date of operation</th>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
    </thead>
    <tbody class="budget-index">
      <%= render "index" %>
    </tbody>
  </table>
  <%= will_paginate @budgets %>
</div>
<div id="budget-modal" class="modal fade">
  <div class="modal-dialog">
    <div id="inner-budget-modal" class="modal-content"></div>
  </div>
</div>

app/views/budgets/new.js.erb
$("#inner-budget-modal").html("<%= escape_javascript(render 'new') %>")
$("#budget-modal").modal("show")

app/views/budgets/update.js.erb
<%= render "save" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Budget</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <% flash.each do |type, value| %>
        <div class="<%= flash_class(type) %>" id="flash">
              <%= value %>
        </div>
   <% end %>

    <%= render 'shared/navigation_bar' %>
    
    <%= yield %>
    <div id="footer">
      <div class = "navbar navbar-default navbar-fixed-bottom">

        <div class = "container">
          <p class = "navbar-text pull-left">Application Build By Dmitry Kowalewski &copy; 2015</p>
          <a href = "https://github.com/dkov88/my_finances" class = "navbar-btn btn btn-info pull-right">View on GitHub</a>
        </div>

      </div>
    </div>
  </body>
</html>

app/views/shared/_navigation_bar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <h3>
        <%= link_to "My Budget App", budgets_path, style: "text-decoration: none" %>
      </h3>
    </div>

    <p class="navbar-text pull-right">
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path, class: 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, class: 'navbar-link'  %>
    <% end %>
  </div>
</nav>

app/views/wallets/_form.html.erb
<%= form_for(@wallet, html: {class: 'form-horizontal'}) do |f| %>
      
  <div class="form-group">
    <%= f.check_box :income, :checked => true %> 
    <%= label :income, 'Income' %>
  </div>
      
  <div class="form-group">
    <%= f.check_box :expense %>
    <%= label :expense, 'Expense' %>
  </div>

  <%= f.submit "#{action_name.capitalize} wallet", class: "btn btn-success" %>
<% end %>

app/views/wallets/create.html.erb
<h1>Wallets#create</h1>
<p>Find me in app/views/wallets/create.html.erb</p>

app/views/wallets/edit.html.erb
<div class="container" >
  <div class="col-md-2 col-md-offset-5">
    <h2 class="text-muted">Update wallet</h2>
    <hr/>
    <%= render "form" %>
  </div>
</div>

app/views/wallets/new.html.erb
<div class="container" >
  <div class="content">
    <h2 class="text-muted">Create new wallet</h2>
    <hr/>
    <%= form_for(@wallet, html: {class: 'form-horizontal'}) do |f| %>
      
      <div class="form-group">
        <%= f.check_box :income, :checked => true %> 
        <%= label :income, 'Income' %>
      </div>
      
      <div class="form-group">
        <%= f.check_box :expense %>
        <%= label :expense, 'Expense' %>
      </div>

      <%= f.submit "Create", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/wallets/show.html.erb
<h1>Wallets#show</h1>
<p>Find me in app/views/wallets/show.html.erb</p>

app/views/wallets/update.html.erb
<h1>Wallets#update</h1>
<p>Find me in app/views/wallets/update.html.erb</p>